### PR TITLE
Create livestream folder and reference client implementation; move REST API client into designated folder

### PR DESCRIPTION
**Pull request by rbuck23**
## Description

I've added a reference implementation to highlight:

- The need to handle redirects
- Data processing performed in a separate thread
- Common HTTP response codes

## Motivation and Context

This is related to moving Adobe Livestream to be under the umbrella of the Analytics 2.0 APIs. With the updated documentation, we have created an updated reference client implementation.

## How Has This Been Tested?

I have built and run this successfully many times locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rbuck23** [comment]
@gigazelle @johnwight Here is the reference Livestream consumer implementation. I've also refactored how the java folder is laid out by putting the existing API client into it's own rest-api folder. This now sits alongside the livestream folder.

**Comment by johnwight** [comment]
This was handled and implemented into the Livestream docs separately. I'm closing this. Please let me know if I'm missing something.

**Comment by rbuck23** [comment]
@johnwight I think this still needs to be merged in as this is not documentation, this is the sample client application for customers to reference.

**Comment by johnwight** [comment]
I have added rbuck's java and pom files in another merge.

**Pull request closed without merging**
