### PR TITLE
Added multi-level breakdown example

### PR DESCRIPTION
**Pull request by mike2184**
@johnwight - Would you review this?

### CODE REVIEW

**Comment by johnwight** [comment]
Is there a checklist I should review or should this be just an automatic click on Merge?

**Comment by johnwight** [comment]
This looks like a great doc. Should I go ahead and click Merge pull request and apply any style editing afterwards? That would get it out there sooner.

**Comment by mike2184** [comment]
@johnwight - I went ahead and merged it so you can make any style editing changes you would like now.

**Comment by johnwight** [comment]
Sorry for the delay. These messages go to my personal email and I had not
checked it today.

**Pull request merged**
